export const DATA_TABLE_FIELD_TYPE_ENUMS = [
	'TEXT',
	'ID',
	'ID_OR_TEXT',
	'NUMBER',
	'PRICE',
	'BOOLEAN',
	'DATE',
	'WEEK_OF_MON',
	'WEEK_OF_SUN',
	'DATETIME',
	'SELECT',
	'SELECT_OR_TEXT',
	'MULTI_SELECT',
	'JSON',
] as const;

export const DATA_TABLE_COLUMN_WIDTH = 160;
export const DATA_TABLE_COLUMN_MIN_WIDTH = 72;
export const DATA_TABLE_COLUMN_MAX_WIDTH = 640;
export const DATA_TABLE_HUMAN_LABEL_MAX_LENGTH = 70;
export const DATA_TABLE_ROWS_MAX_LIMIT = 400;
