export const SHEET_CELL_SOURCE_TYPE_ENUMS = [
	'USER',
	'REGION_GENERATED',
	'REGION_OVERRIDE',
] as const;

export const SHEET_REGION_TYPE_ENUMS = [
	'DATA_TABLE',
] as const;

export const SHEET_REGION_CONFLICT_POLICY_ENUMS = [
	'TRUNCATE_AT_FIRST_BLOCKER',
	'OVERWRITE',
] as const;

export const SHEET_STRUCTURE_OPERATION_ENUMS = [
	'INSERT_ROW_ABOVE',
	'INSERT_COLUMN_LEFT',
	'DELETE_ROW',
	'DELETE_COLUMN',
] as const;

export const WORKSPACE_ITEM_SORT_ENUMS = [
	'UPDATED_AT_DESC',
	'TITLE_ASC',
] as const;

export const WORKSPACE_ITEM_LIST_LIMIT = 1000;
export const SHEET_DATA_TABLE_REGION_MAX_ROWS = 1000;
export const SHEET_DEFAULT_ROW_COUNT = 1000;
export const SHEET_DEFAULT_COLUMN_COUNT = 26;
export const SHEET_VIEWPORT_MAX_ROWS = 400;
export const SHEET_VIEWPORT_MAX_COLUMNS = 100;
export const SHEET_DEFAULT_COLUMN_WIDTH = 160;
export const SHEET_DEFAULT_ROW_HEIGHT = 28;

export const BUILT_IN_DATA_TABLE_NAMES = [
  'organizations',
  'orgs',
];
