import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const cssDir = path.resolve(__dirname, '../css');
const responsiveSourcePath = path.join(cssDir, '_responsive.css');
const responsiveOutputPath = path.join(cssDir, '_responsive.generated.css');
const colorsOutputPath = path.join(cssDir, '_colors.generated.css');

const responsiveBreakpoints = [
  ['landscape', '--responsive-mobile-landscape'],
  ['portrait', '--responsive-mobile-portrait'],
  ['phone', '--responsive-phone-wide'],
  ['narrow', '--responsive-phone-narrow'],
  ['tiny', '--responsive-phone-tiny'],
];

const colorPalettes = [
  'red',
  'orange',
  'brown',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose',
  'slate',
  'zinc',
  'stone',
];

const colorShades = [
  ['fd', 'fade'],
  ['lt', 'light'],
  ['md', 'medium'],
  ['bd', 'bold'],
  ['', 'default'],
];

const colorRuleGroups = [
  ['cl', 'color'],
  ['bg', 'background-color'],
  ['bd', 'border-color'],
];

/*
Reads the source responsive utility CSS file that will be expanded into
breakpoint-scoped utility classes.
*/
async function readSourceCSS() {
  return readFile(responsiveSourcePath, 'utf8');
}

/*
Extracts simple single-selector utility rules from the source CSS file so each
selector can be cloned with responsive prefixes.
*/
function parseUtilityRules(sourceCSS) {
  const utilityRulePattern = /(^|\n)\s*(\.[A-Za-z0-9_-][A-Za-z0-9_-]*)\s*\{([^}]*)\}/g;

  return Array.from(
    sourceCSS.matchAll(utilityRulePattern),
    ([, , selector, declarations]) => ({
      selector,
      declarations: declarations.trim(),
    })
  );
}

/*
Builds the generated CSS file contents by wrapping cloned utility selectors in
their corresponding custom-media breakpoints.
*/
function buildGeneratedResponsiveCSS(rules) {
  const sections = responsiveBreakpoints.map(([prefix, mediaName]) => {
    const clonedRules = rules.map(({ selector, declarations }) => {
      const className = selector.slice(1);

      return `  .${prefix}\\:${className} { ${declarations} }`;
    });

    return `@media (${mediaName}) {\n${clonedRules.join('\n')}\n}`;
  });

  return [
    '/* This file is auto-generated by scripts/generateResponsiveCss.js. */',
    '/* Do not edit this file directly. Edit _responsive.css and regenerate. */',
    '',
    ...sections,
    '',
  ].join('\n');
}

/*
Builds one palette utility rule for a color, shade, and CSS property group.
Default background rules also set a readable foreground color.
*/
function buildColorRule(rulePrefix, propertyName, palette, classSuffix, tokenSuffix) {
  const shadeClassSuffix = classSuffix ? `_${classSuffix}` : '';
  const className = `${rulePrefix}_${palette}${shadeClassSuffix}`;
  const selectors = [
    `.${className}`,
    `.${className}_hv:hover`,
  ];
  const declarations = [
    `${propertyName}: var(--color-${palette}-${tokenSuffix}) !important;`,
  ];

  if (rulePrefix === 'bg' && tokenSuffix === 'default') {
    declarations.push('color: var(--color-solid) !important;');
  }

  return `${selectors.join(', ')} { ${declarations.join(' ')} }`;
}

/*
Builds the generated color utility CSS file contents from palette, shade, and
property rule definitions.
*/
function buildGeneratedColorsCSS() {
  const sections = colorRuleGroups.map(([rulePrefix, propertyName]) => {
    const rules = colorPalettes.flatMap((palette) => {
      return colorShades.map(([classSuffix, tokenSuffix]) => {
        return buildColorRule(
          rulePrefix,
          propertyName,
          palette,
          classSuffix,
          tokenSuffix
        );
      });
    });

    return rules.join('\n');
  });

  return [
    '/* This file is auto-generated by scripts/generateResponsiveCss.js. */',
    '/* Do not edit this file directly. Update the color generator definitions and regenerate. */',
    '',
    '/* Colors - Palette */',
    '',
    ...sections,
    '',
  ].join('\n');
}

/*
Writes a generated CSS file to the shared CSS package so apps can import it
through the existing global stylesheet.
*/
async function writeGeneratedCSS(outputPath, outputCSS) {
  await mkdir(cssDir, { recursive: true });
  await writeFile(outputPath, outputCSS, 'utf8');
}

/*
Generates the shared CSS files that can be derived from compact utility
definitions.
*/
async function main() {
  const sourceCSS = await readSourceCSS();
  const rules = parseUtilityRules(sourceCSS);
  const responsiveOutputCSS = buildGeneratedResponsiveCSS(rules);
  const colorsOutputCSS = buildGeneratedColorsCSS();

  await Promise.all([
    writeGeneratedCSS(responsiveOutputPath, responsiveOutputCSS),
    writeGeneratedCSS(colorsOutputPath, colorsOutputCSS),
  ]);

  console.log(`Generated ${path.relative(process.cwd(), responsiveOutputPath)} from ${path.relative(process.cwd(), responsiveSourcePath)}.`);
  console.log(`Generated ${path.relative(process.cwd(), colorsOutputPath)} from color generator definitions.`);
}

await main();
