import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const cssDir = path.resolve(__dirname, '../css');
const sourcePath = path.join(cssDir, '_responsive.css');
const outputPath = path.join(cssDir, '_responsive.generated.css');

const responsiveBreakpoints = [
  ['landscape', '--responsive-mobile-landscape'],
  ['portrait', '--responsive-mobile-portrait'],
  ['phone', '--responsive-phone-wide'],
  ['narrow', '--responsive-phone-narrow'],
  ['tiny', '--responsive-phone-tiny'],
];

/*
Reads the source responsive utility CSS file that will be expanded into
breakpoint-scoped utility classes.
*/
async function readSourceCSS() {
  return readFile(sourcePath, 'utf8');
}

/*
Extracts simple single-selector utility rules from the source CSS file so each
selector can be cloned with responsive prefixes.
*/
function parseUtilityRules(sourceCSS) {
  const utilityRulePattern = /(^|\n)\s*(\.[A-Za-z0-9_-][A-Za-z0-9_-]*)\s*\{([^}]*)\}/g;

  return Array.from(
    sourceCSS.matchAll(utilityRulePattern),
    ([, , selector, declarations]) => ({
      selector,
      declarations: declarations.trim(),
    })
  );
}

/*
Builds the generated CSS file contents by wrapping cloned utility selectors in
their corresponding custom-media breakpoints.
*/
function buildGeneratedCSS(rules) {
  const sections = responsiveBreakpoints.map(([prefix, mediaName]) => {
    const clonedRules = rules.map(({ selector, declarations }) => {
      const className = selector.slice(1);

      return `  .${prefix}\\:${className} { ${declarations} }`;
    });

    return `@media (${mediaName}) {\n${clonedRules.join('\n')}\n}`;
  });

  return [
    '/* This file is auto-generated by scripts/generateResponsiveCss.js. */',
    '/* Do not edit this file directly. Edit _responsive.css and regenerate. */',
    '',
    ...sections,
    '',
  ].join('\n');
}

/*
Writes the generated responsive utility CSS file to the shared CSS package so
apps can import it through the existing global stylesheet.
*/
async function writeGeneratedCSS(outputCSS) {
  await mkdir(cssDir, { recursive: true });
  await writeFile(outputPath, outputCSS, 'utf8');
}

/*
Generates the breakpoint-prefixed utility classes from the shared responsive
utility source file.
*/
async function main() {
  const sourceCSS = await readSourceCSS();
  const rules = parseUtilityRules(sourceCSS);
  const outputCSS = buildGeneratedCSS(rules);

  await writeGeneratedCSS(outputCSS);

  console.log(`Generated ${path.relative(process.cwd(), outputPath)} from ${path.relative(process.cwd(), sourcePath)}.`);
}

await main();
